# Generated by Django 5.2.6 on 2026-01-21 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('explanation_text', models.TextField(default='This study involves participation in interactive experiments using the SHARPIE (Shared Human-AI Reinforcement Learning Platform for Interactive Experiments) platform. You will interact with AI agents in reinforcement learning environments. The experiment typically takes 15-30 minutes to complete, depending on the specific experiment configuration.', max_length=1000)),
                ('research_team', models.JSONField(default={'main': {'designation': 'Principal investigator', 'email': 'principal.investigator@example.com', 'institution': 'Hybrid Intelligence Centre', 'location': 'The Netherlands'}})),
                ('ethical_guidelines', models.TextField(default='This project adheres to the ethical guidelines established by The Hybrid Intelligence Centre, and falls under fundamental research without any commercial purpose nor external stakeholders or partners. For details of our legal basis for using personal data and the rights you have over your data, please see the privacy information at HI Centre Ethics Policy (PDF).', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('demographics', models.JSONField(blank=True, null=True)),
                ('agreed_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('consent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='accounts.consent')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='participant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
