# Generated by Django 5.2.3 on 2025-08-04 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Info_Tamer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=60)),
                ('step', models.IntegerField(default=-1)),
                ('reward', models.FloatField(default=0.0)),
                ('changed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TAMER', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
