# Generated by Django 5.2.6 on 2026-02-12 07:15

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Runner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_key', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(default='never connected', max_length=20, verbose_name='Status')),
                ('last_active', models.DateTimeField(blank=True, db_default=django.db.models.functions.datetime.Now(), null=True, verbose_name='Last active')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='data.session')),
            ],
        ),
    ]
