[fcgi-program:asgi]
socket=tcp://localhost:8000

directory=/my/app/path/webserver/

environment=PATH=/path/to/venv/bin/

command=/bin/bash -c "/bin/mkdir -p /run/daphne && exec daphne -u /run/daphne/daphne%(process_num)d.sock --fd 0 --access-log - --proxy-headers mysite.asgi:application"

numprocs=1

process_name=asgi%(process_num)d

autostart=true
autorestart=true

stdout_logfile=/your/log/asgi.log
redirect_stderr=true