# Generated by Django 5.2.6 on 2026-02-12 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('experiment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(null=True)),
                ('duration_steps', models.IntegerField(null=True)),
                ('completed', models.BooleanField(default=False)),
                ('outcome', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_index', models.IntegerField()),
                ('state', models.JSONField(blank=True, null=True)),
                ('action', models.JSONField(blank=True, null=True)),
                ('reward', models.JSONField(blank=True, null=True)),
                ('info', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='records', to='data.episode')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=100)),
                ('connected_participants', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('not_ready', 'Not ready'), ('ready', 'Ready'), ('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('aborted', 'Aborted')], default='not_ready', max_length=15)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sessions', to='experiment.experiment')),
                ('participants', models.ManyToManyField(related_name='sessions', to='accounts.participant')),
            ],
        ),
        migrations.AddField(
            model_name='episode',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='episodes', to='data.session'),
        ),
    ]
