# Generated by Django 5.2.15 on 2026-06-08 11:31

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consent',
            name='research_team',
            field=models.JSONField(default=accounts.models.default_research_team),
        ),
    ]
